# Generated by Django 2.0.5 on 2018-05-15 05:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20180511_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='username',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 15, 5, 42, 20, 711026, tzinfo=utc), null=True),
        ),
    ]
