# Generated by Django 2.0.5 on 2018-05-15 05:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20180515_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='username',
            new_name='super_obj',
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 15, 5, 54, 54, 300391, tzinfo=utc), null=True),
        ),
    ]
