# Generated by Django 2.0.5 on 2018-05-15 06:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20180515_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 15, 6, 58, 44, 538649, tzinfo=utc), null=True),
        ),
    ]
