# Generated by Django 2.0.5 on 2018-05-04 10:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_auto_20180504_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 4, 10, 55, 46, 998134, tzinfo=utc), null=True),
        ),
    ]
