# Generated by Django 2.0.5 on 2018-05-07 12:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0009_auto_20180507_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 7, 12, 9, 56, 570485, tzinfo=utc), null=True),
        ),
    ]
