# Generated by Django 2.0.5 on 2018-05-08 06:47

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0012_auto_20180508_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='User_type',
            field=models.CharField(choices=[('USR', 'User'), ('SPR', 'superuser')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 8, 6, 46, 46, 756239, tzinfo=utc), null=True),
        ),
    ]
