# Generated by Django 2.0.5 on 2018-05-08 08:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0015_auto_20180508_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='User_type',
        ),
        migrations.AlterField(
            model_name='blog',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 5, 8, 8, 29, 29, 840582, tzinfo=utc), null=True),
        ),
    ]
